
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "XML parser"
documentation = "https://rustdoc.swc.rs/swc_xml_parser/"
edition = "2021"
include = ["Cargo.toml","src/**/*.rs","src/**/*.json"]
license = "Apache-2.0"
name = "ad_swc_xml_parser"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_xml_parser"

[lib]
bench = false

[features]
debug = []

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"

[dependencies.swc_xml_ast]
version = "1.0.0"
path = "../swc_xml_ast"
package = "ad_swc_xml_ast"

[dev-dependencies]
serde = "1.0.127"
serde_json = "1.0.66"

[dev-dependencies.swc_xml_ast]
version = "1.0.0"
path = "../swc_xml_ast"
features = ["serde-impl"]
package = "ad_swc_xml_ast"

[dev-dependencies.swc_xml_visit]
version = "1.0.0"
path = "../swc_xml_visit"
package = "ad_swc_xml_visit"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"
