
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "Internal macro for the html code generator"
documentation = "https://rustdoc.swc.rs/swc_html_codegen_macros/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_html_codegen_macros"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html_codegen_macros"

[lib]
bench = false
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "2"
features = ["fold"]

[dependencies.swc_macros_common]
version = "1.0.0"
path = "../swc_macros_common"
package = "ad_swc_macros_common"
