
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "AST definitions of html"
documentation = "https://rustdoc.swc.rs/swc_html_ast/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_html_ast"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html_ast"

[lib]
bench = false

[features]
__rkyv = []
rkyv-impl = ["__rkyv","rkyv","swc_atoms/rkyv-impl","swc_common/rkyv-impl"]
serde-impl = ["serde"]

[dependencies]
is-macro = "0.3.0"

[dependencies.rkyv]
version = "=0.7.42"
optional = true
features = ["strict","validation"]

[dependencies.serde]
version = "1.0.127"
features = ["derive"]
optional = true

[dependencies.string_enum]
version = "1.0.0"
path = "../string_enum/"
package = "ad_string_enum"

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"
