
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Timings for swc"
documentation = "https://rustdoc.swc.rs/swc_timer/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_timer"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_timer"

[lib]
bench = false

[dependencies]
tracing = "0.1.37"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"
