
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Daniel Woznicki <daniel.woznicki@gmail.com>"]
description = "Implementation of Comments of swc_common"
documentation = "https://rustdoc.swc.rs/swc_node_comments/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_node_comments"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_node_comments"

[lib]
bench = false

[dependencies]
dashmap = "5.4.0"

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"
