
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "HTML code generator for the swc project"
documentation = "https://rustdoc.swc.rs/swc_html_codegen/"
edition = "2021"
include = ["Cargo.toml","src/**/*.rs"]
license = "Apache-2.0"
name = "ad_swc_html_codegen"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html_codegen"

[lib]
bench = false

[dependencies]
auto_impl = "1.1.0"
bitflags = "2.3.2"
rustc-hash = "1.1.0"

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"

[dependencies.swc_html_ast]
version = "1.0.0"
path = "../swc_html_ast"
package = "ad_swc_html_ast"

[dependencies.swc_html_codegen_macros]
version = "1.0.0"
path = "../swc_html_codegen_macros"
package = "ad_swc_html_codegen_macros"

[dependencies.swc_html_utils]
version = "1.0.0"
path = "../swc_html_utils"
package = "ad_swc_html_utils"

[dev-dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
features = ["sourcemap"]
package = "ad_swc_common"

[dev-dependencies.swc_html_parser]
version = "1.0.0"
path = "../swc_html_parser"
package = "ad_swc_html_parser"

[dev-dependencies.swc_html_visit]
version = "1.0.0"
path = "../swc_html_visit"
package = "ad_swc_html_visit"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"
