
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Proxy structs to the hosts original structs for the plugin"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_plugin_proxy"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_plugin_proxy"

[lib]
bench = false

[features]
__rkyv = []
rkyv-impl = ["__rkyv","rkyv"]
__plugin_mode = []
__plugin_rt = []
plugin-mode = ["__plugin_mode","swc_common/plugin-base","rkyv-impl"]
plugin-rt = ["__plugin_rt","swc_common/plugin-base","rkyv-impl"]

[dependencies]
tracing = "0.1.37"

[dependencies.rkyv]
package = "rkyv"
version = "=0.7.42"
optional = true
features = ["strict","validation"]

[dependencies.better_scoped_tls]
version = "1.0.0"
path = "../better_scoped_tls"
package = "ad_better_scoped_tls"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"

[dependencies.swc_ecma_ast]
version = "1.0.0"
path = "../swc_ecma_ast"
package = "ad_swc_ecma_ast"

[dependencies.swc_trace_macro]
version = "1.0.0"
path = "../swc_trace_macro"
package = "ad_swc_trace_macro"
