
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Macro support for authoring plugin's transform fn"
documentation = "https://rustdoc.swc.rs/swc_plugin_macro/"
edition = "2018"
license = "Apache-2.0"
name = "ad_swc_plugin_macro"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_plugin_macro"

[lib]
bench = false
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "2"
features = ["full"]
