
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "HTML minifier"
documentation = "https://rustdoc.swc.rs/swc_html_minifier/"
edition = "2021"
include = ["Cargo.toml","src/**/*.rs","data/**/*.json"]
license = "Apache-2.0"
name = "ad_swc_html_minifier"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html_minifier"

[lib]
bench = false

[dependencies]
once_cell = "1.18.0"
serde_json = "1.0.61"

[dependencies.serde]
version = "1.0.118"
features = ["derive"]

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_cached]
version = "1.0.0"
path = "../swc_cached"
package = "ad_swc_cached"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"

[dependencies.swc_css_ast]
version = "1.0.0"
path = "../swc_css_ast"
package = "ad_swc_css_ast"

[dependencies.swc_css_codegen]
version = "1.0.0"
path = "../swc_css_codegen"
package = "ad_swc_css_codegen"

[dependencies.swc_css_minifier]
version = "1.0.0"
path = "../swc_css_minifier"
package = "ad_swc_css_minifier"

[dependencies.swc_css_parser]
version = "1.0.0"
path = "../swc_css_parser"
package = "ad_swc_css_parser"

[dependencies.swc_ecma_ast]
version = "1.0.0"
path = "../swc_ecma_ast"
package = "ad_swc_ecma_ast"

[dependencies.swc_ecma_codegen]
version = "1.0.0"
path = "../swc_ecma_codegen"
features = ["serde-impl"]
package = "ad_swc_ecma_codegen"

[dependencies.swc_ecma_minifier]
version = "1.0.0"
path = "../swc_ecma_minifier"
features = ["extra-serde"]
package = "ad_swc_ecma_minifier"

[dependencies.swc_ecma_parser]
version = "1.0.0"
path = "../swc_ecma_parser"
package = "ad_swc_ecma_parser"

[dependencies.swc_ecma_transforms_base]
version = "1.0.0"
path = "../swc_ecma_transforms_base"
package = "ad_swc_ecma_transforms_base"

[dependencies.swc_ecma_visit]
version = "1.0.0"
path = "../swc_ecma_visit"
package = "ad_swc_ecma_visit"

[dependencies.swc_html_ast]
version = "1.0.0"
path = "../swc_html_ast"
package = "ad_swc_html_ast"

[dependencies.swc_html_codegen]
version = "1.0.0"
path = "../swc_html_codegen"
package = "ad_swc_html_codegen"

[dependencies.swc_html_parser]
version = "1.0.0"
path = "../swc_html_parser"
package = "ad_swc_html_parser"

[dependencies.swc_html_utils]
version = "1.0.0"
path = "../swc_html_utils"
package = "ad_swc_html_utils"

[dependencies.swc_html_visit]
version = "1.0.0"
path = "../swc_html_visit"
package = "ad_swc_html_visit"

[dev-dependencies]
criterion = "0.5"

[dev-dependencies.swc_malloc]
version = "1.0.0"
path = "../swc_malloc"
package = "ad_swc_malloc"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"

[[bench]]
harness = false
name = "full"
