
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
build = "build.rs"
description = "Speedy web compiler"
documentation = "https://rustdoc.swc.rs/swc/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_node_bundler"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_node_bundler"

[lib]
bench = false

[features]
default = ["swc_v1"]
serde-impl = ["serde"]
swc_v1 = ["serde-impl"]
swc_v2 = ["serde-impl"]

[dependencies]
anyhow = "1"
dashmap = "5.4.0"
is-macro = "0.3.0"
once_cell = "1.18.0"
regex = "1"
serde_json = "1"
tracing = "0.1.37"

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.string_enum]
version = "1.0.0"
path = "../string_enum"
package = "ad_string_enum"

[dependencies.swc]
version = "1.0.0"
path = "../swc"
package = "ad_swc"

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_bundler]
version = "1.0.0"
path = "../swc_bundler"
features = ["concurrent"]
package = "ad_swc_bundler"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
features = ["concurrent"]
package = "ad_swc_common"

[dependencies.swc_ecma_ast]
version = "1.0.0"
path = "../swc_ecma_ast"
package = "ad_swc_ecma_ast"

[dependencies.swc_ecma_codegen]
version = "1.0.0"
path = "../swc_ecma_codegen"
package = "ad_swc_ecma_codegen"

[dependencies.swc_ecma_loader]
version = "1.0.0"
path = "../swc_ecma_loader"
package = "ad_swc_ecma_loader"

[dependencies.swc_ecma_parser]
version = "1.0.0"
path = "../swc_ecma_parser"
package = "ad_swc_ecma_parser"

[dependencies.swc_ecma_transforms]
version = "1.0.0"
path = "../swc_ecma_transforms"
package = "ad_swc_ecma_transforms"

[dependencies.swc_ecma_utils]
version = "1.0.0"
path = "../swc_ecma_utils"
package = "ad_swc_ecma_utils"

[dependencies.swc_ecma_visit]
version = "1.0.0"
path = "../swc_ecma_visit"
package = "ad_swc_ecma_visit"

[dependencies.swc_malloc]
version = "1.0.0"
path = "../swc_malloc"
package = "ad_swc_malloc"

[dev-dependencies]
pretty_assertions = "1.3"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"
