
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Runner for swc plugins. This crate is INTERNAL crate and used by swc itself."
documentation = "https://rustdoc.swc.rs/swc_plugin_runner/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_plugin_runner"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_plugin_runner"

[lib]
bench = false
doctest = false

[features]
default = ["filesystem_cache","plugin_transform_host_native"]
plugin_transform_host_js = ["wasmer/js-default","wasmer-wasix/js-default","wasmer-compiler-cranelift/wasm"]
plugin_transform_host_native = ["wasmer/default","wasmer-wasix/sys","wasmer-wasix/logging","wasmer-wasix/host-fs","wasmer-wasix/sys-poll","wasmer-wasix/sys-thread","wasmer-wasix/host-threads","wasmer-compiler-cranelift/default"]
plugin_transform_host_native_shared_runtime = ["tokio"]
filesystem_cache = ["wasmer-cache"]
plugin_transform_schema_v1 = ["swc_common/plugin_transform_schema_v1"]
plugin_transform_schema_vtest = ["swc_common/plugin_transform_schema_vtest"]
ecma = ["swc_ecma_ast/rkyv-impl"]
css = ["swc_css_ast/rkyv-impl"]
__rkyv = []
rkyv-impl = ["__rkyv","swc_common/plugin-rt","swc_plugin_proxy/plugin-rt"]

[dependencies]
anyhow = "1.0.71"
enumset = "1.1.2"
once_cell = "1.18.0"
parking_lot = "0.12.1"
serde_json = "1.0.64"
tracing = "0.1.37"

[dependencies.futures]
version = "0.3"

[dependencies.serde]
version = "1.0.126"
features = ["derive"]

[dependencies.tokio]
version = "1"
default-features = false
optional = true

[dependencies.wasmer]
version = "4.2.5"
default-features = false

[dependencies.wasmer-wasix]
version = "0.18.0"
default-features = false

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
features = ["concurrent"]
package = "ad_swc_common"

[dependencies.swc_css_ast]
version = "1.0.0"
path = "../swc_css_ast"
optional = true
package = "ad_swc_css_ast"

[dependencies.swc_ecma_ast]
version = "1.0.0"
path = "../swc_ecma_ast"
optional = true
package = "ad_swc_ecma_ast"

[dependencies.swc_plugin_proxy]
version = "1.0.0"
path = "../swc_plugin_proxy"
package = "ad_swc_plugin_proxy"

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.wasmer-cache]
version = "4.0.0"
optional = true

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.wasmer-compiler-cranelift]
version = "4.0.0"
default-features = false

[dev-dependencies]
criterion = "0.5"

[dev-dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dev-dependencies.swc_css_ast]
version = "1.0.0"
path = "../swc_css_ast"
features = ["rkyv-impl"]
package = "ad_swc_css_ast"

[dev-dependencies.swc_css_parser]
version = "1.0.0"
path = "../swc_css_parser"
package = "ad_swc_css_parser"

[dev-dependencies.swc_ecma_ast]
version = "1.0.0"
path = "../swc_ecma_ast"
features = ["rkyv-impl"]
package = "ad_swc_ecma_ast"

[dev-dependencies.swc_ecma_loader]
version = "1.0.0"
path = "../swc_ecma_loader"
package = "ad_swc_ecma_loader"

[dev-dependencies.swc_ecma_parser]
version = "1.0.0"
path = "../swc_ecma_parser"
package = "ad_swc_ecma_parser"

[dev-dependencies.swc_ecma_visit]
version = "1.0.0"
path = "../swc_ecma_visit"
package = "ad_swc_ecma_visit"

[dev-dependencies.swc_malloc]
version = "1.0.0"
path = "../swc_malloc"
package = "ad_swc_malloc"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"

[dev-dependencies.tokio]
version = "1"
features = ["rt"]

[[bench]]
harness = false
name = "ecma_invoke"
