
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "HTML parser"
documentation = "https://rustdoc.swc.rs/swc_html_parser/"
edition = "2021"
include = ["Cargo.toml","src/**/*.rs","src/**/*.json"]
license = "Apache-2.0"
name = "ad_swc_html_parser"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html_parser"

[lib]
bench = false

[features]
debug = []

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"

[dependencies.swc_html_ast]
version = "1.0.0"
path = "../swc_html_ast"
package = "ad_swc_html_ast"

[dependencies.swc_html_utils]
version = "1.0.0"
path = "../swc_html_utils"
package = "ad_swc_html_utils"

[dev-dependencies]
criterion = "0.5"
serde = "1.0.127"
serde_json = "1.0.66"

[dev-dependencies.swc_html_ast]
version = "1.0.0"
path = "../swc_html_ast"
features = ["serde-impl"]
package = "ad_swc_html_ast"

[dev-dependencies.swc_html_visit]
version = "1.0.0"
path = "../swc_html_visit"
package = "ad_swc_html_visit"

[dev-dependencies.swc_malloc]
version = "1.0.0"
path = "../swc_malloc"
package = "ad_swc_malloc"

[dev-dependencies.testing]
version = "1.0.0"
path = "../testing"
package = "ad_testing"

[[bench]]
harness = false
name = "compare"

[[bench]]
harness = false
name = "lexer"

[[bench]]
harness = false
name = "parser"
