
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Base for swc plugins"
documentation = "https://rustdoc.swc.rs/swc_plugin_testing/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_plugin_testing"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_plugin_testing"

[lib]
bench = false

[dependencies]
