
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "Common code for SWC bindings"
documentation = "https://rustdoc.swc.rs/swc_binding_utils/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_nodejs_common"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_nodejs_common"

[lib]
bench = false

[dependencies]
anyhow = "1"

[dependencies.napi]
version = "2"
default-features = false
features = ["napi3","serde-json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"
features = ["unbounded_depth"]

[dependencies.tracing]
version = "0.1.37"

[dependencies.tracing-subscriber]
version = "0.3.17"
features = ["env-filter"]
