
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "HTML apis for rust"
documentation = "https://rustdoc.swc.rs/swc_html/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_html"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg","docsrs"]

[lib]
bench = false

[features]
minifier = ["swc_html_minifier"]

[dependencies.swc_html_ast]
version = "1.0.0"
path = "../swc_html_ast"
package = "ad_swc_html_ast"

[dependencies.swc_html_codegen]
version = "1.0.0"
path = "../swc_html_codegen"
package = "ad_swc_html_codegen"

[dependencies.swc_html_minifier]
version = "1.0.0"
path = "../swc_html_minifier"
optional = true
package = "ad_swc_html_minifier"

[dependencies.swc_html_parser]
version = "1.0.0"
path = "../swc_html_parser"
package = "ad_swc_html_parser"

[dependencies.swc_html_visit]
version = "1.0.0"
path = "../swc_html_visit"
package = "ad_swc_html_visit"
