
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "Utils for HTML"
documentation = "https://rustdoc.swc.rs/swc_html_utils/"
edition = "2021"
include = ["Cargo.toml","src/**/*.rs","data/**/*.json"]
license = "Apache-2.0"
name = "ad_swc_html_utils"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_html_utils"

[lib]
bench = false

[dependencies]
once_cell = "1.18.0"
serde_json = "1.0.61"

[dependencies.serde]
version = "1.0.118"
features = ["derive"]

[dependencies.swc_atoms]
version = "1.0.0"
path = "../swc_atoms"
package = "ad_swc_atoms"

[dependencies.swc_common]
version = "1.0.0"
path = "../swc_common"
package = "ad_swc_common"
