
[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>","Alexander Akait <sheo13666q@gmail.com>"]
description = "XML apis for rust"
documentation = "https://rustdoc.swc.rs/swc_xml/"
edition = "2021"
license = "Apache-2.0"
name = "ad_swc_xml"
repository = "https://github.com/swc-project/swc.git"
version = "1.0.0"
_name = "swc_xml"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg","docsrs"]

[lib]
bench = false

[dependencies.swc_xml_ast]
version = "1.0.0"
path = "../swc_xml_ast"
package = "ad_swc_xml_ast"

[dependencies.swc_xml_codegen]
version = "1.0.0"
path = "../swc_xml_codegen"
package = "ad_swc_xml_codegen"

[dependencies.swc_xml_parser]
version = "1.0.0"
path = "../swc_xml_parser"
package = "ad_swc_xml_parser"

[dependencies.swc_xml_visit]
version = "1.0.0"
path = "../swc_xml_visit"
package = "ad_swc_xml_visit"
